# -*- coding: utf-8 -*-
"""백준15596

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16YKKUpj6Fo_Z8LZLRiQkhRa9kIHRlOc0
"""

def solve(a):
    sum = 0
    for x in a:
        sum += x
    return sum