# -*- coding: utf-8 -*-
"""백준5585

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZUCQLhrTHGHcQHdaDRURSiGJxU_2bnq
"""

# 거스름돈

X = int(input())
a = 1000 - X
b = [500, 100, 50, 10, 5, 1]
cnt = 0

for i in range(len(b)):
    while a >= b[i]:     
        a -= b[i]
        cnt += 1

print(cnt)