# -*- coding: utf-8 -*-
"""백준10871

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CS7gy9G1fKBAB3ulLES6KeSoerrgijhj
"""

N, X = map(int, input().split())
A = list(map(int, input().split()))
for i in A:
    if i < X:
        print(i, end=' ')