# -*- coding: utf-8 -*-
"""백준1110

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zzhQuzAVztBK8nu_hAEuy_bO5DUDFq1f
"""

# 더하기 사이클

n = int(input())
cnt = 1

t10 = n // 10
t1 = n % 10
m = t10 + t1
t = t1*10 + m%10

while n != t:
    t10 = t // 10
    t1 = t % 10
    m = t10 + t1
    t = t1*10 + m%10
    cnt += 1

print(cnt)