# -*- coding: utf-8 -*-
"""백준1010

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M5NJ5Tcns4D6-yIXlbprDO-z_leLfQvv
"""

# 다리 놓기
T = int(input())
for i in range(T):
    N, M = map(int, input().split())
    #c = mCn
    factorial, factorial_N, factorial_N1 = 1, 1, 1
    for x in range(M):
        factorial *= x+1
    for x in range(N):
        factorial_N *= x+1
    for x in range(M-N):
        factorial_N1 *= x+1
    c = factorial / (factorial_N*factorial_N1)
    print(int(c))