# -*- coding: utf-8 -*-
"""백준2953

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uv3p8BWN3H6DZwja3TLu9_5SE1QMRDL4
"""

# 나는 요리사다
sum = 0
cook=[]
for i in range(5):
    a, b, c, d = map(int, input().split())
    sum = a+b+c+d
    cook.append(sum)
print(cook.index(max(cook))+1, max(cook))