# -*- coding: utf-8 -*-
"""백준1085

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GcPWrD8ap1q8JKqS8BpprOoDAuRkIcMt
"""

# 직사각형에서 탈출

x, y, w, h = map(int, input().split())
m = min(w-x, h-y, x, y)
print(m)