# -*- coding: utf-8 -*-
"""백준1977

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gF0xTiwQLQ6rd2nNB5pwi0nh4S4YI2bG
"""

# 완전제곱수
M = int(input())
N = int(input())
exit = False
sum = 0
for i in range(M, N+1):
    if (i**(1/2)) % 1 == 0:
        if sum == 0:
            min = i
        sum += i
        exit = True
if exit == True:
    print(sum)
    print(min)
else:
    print(-1)