# -*- coding: utf-8 -*-
"""백준1000

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15855ZAkg-X_BsnxsPfC-pOyfpEOziXvZ
"""

# A + B
A, B = map(int, input().split())
print(A+B)