# -*- coding: utf-8 -*-
"""백준5598

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uFb2xSnI6ke7Fu6xD-Zq_-QX4EbsrjMq
"""

# 카이사르 암호
word = input()
for i in word:
    if i == 'A' or i == 'B' or i == 'C':
        print(chr(ord(i)+23), end='')
    else:
        print(chr(ord(i)-3), end='')