# -*- coding: utf-8 -*-
"""백준2839

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12U3BV3ZpGndGPs11ePBXzdjApqxFrK03
"""

# 설탕 배달
N = int(input())
cnt3 = 0
cnt5 = N//5
while N - 3*cnt3 != 5*cnt5:
    cnt5 = (N - 3*cnt3) // 5
    cnt3 += 1

if cnt5 < 0:
    print(-1)
else:
    print(cnt3+cnt5)