# -*- coding: utf-8 -*-
"""백준1193.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/135YBrDNCIfdbpk-ECnovtFHBOCgo5G3p
"""

# 분수 찾기

X = int(input())
line = 1

while X>line:
    X -= line
    line += 1

if line % 2 == 0: # line이 짝수
    a = X
    b = line - X + 1
else :            # line이 홀수
    b = X
    a = line - X + 1

print(a, b, sep='/')

'''
홀수(x) 분자 : x --> 1 내림차순
        분모 : 1 --> x 오름차순

짝수(y) 분자 : 1 --> y 오름차순
        분모 : y --> 1 내림차순
'''