# -*- coding: utf-8 -*-
"""백준2851

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1soHK5yIDVfB95SM74MKxTvB4GOE3PEdI
"""

# 슈퍼 마리오
sum = 0
mush_list = []
for i in range(10):
    mush = int(input())
    mush_list.append(mush)
i = 0
while sum < 100:
    sum += mush_list[i]
    i += 1
    if i > 9:
        break

if abs(100-sum) > abs(100 - (sum-mush_list[i-1])):
    sum = sum - mush_list[i-1]

print(sum)