# -*- coding: utf-8 -*-
"""백준1181

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18xNT8f07AqrYgSJuPFpoqr_qWJcvjRrq
"""

# 단어 정렬
import sys
input = sys.stdin.readline

words = set()
N = int(input())
for _ in range(N):
    word = input().rstrip()
    words.add(word)

for i in sorted(words, key=lambda x: (len(x),x)):
    print(i)