# -*- coding: utf-8 -*-
"""백준1330

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FQFUrzeOaiejpRG8DbySEYwkz-eUKo6r
"""

# 두 수 비교하기
A, B = map(int, input().split())
if A > B:
    print('>')
elif A < B:
    print('<')
else:
    print('==')