# -*- coding: utf-8 -*-
"""백준10988

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fAYeCME4UoH1BMbyeG7vov35hUAWp2vQ
"""

# 팰린드롬인지 확인하기

s = input()
if s == s[::-1]:
    print(1)
else:
    print(0)