# -*- coding: utf-8 -*-
"""백준4673

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ID0YQqcjRu6BRw-XBsH_fdXa180ClZgP
"""

# 수들의 합

S = int(input())

if S == 1:
    print(1)
for i in range(1, S+1):
    S -= i
    if S < 0:
        print(i-1)
        break