# -*- coding: utf-8 -*-
"""백준1120

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bTeUVnBkqJMB-ECf4VwBTCQUHcQeZkOG
"""

# 문자열
min = 50
A, B = input().split()
for i in range(len(B)-len(A)+1):
    cnt = 0
    for j in range(len(A)):
        if A[j] != B[i+j]:
            cnt += 1
    if min > cnt:
        min = cnt
print(min)