# -*- coding: utf-8 -*-
"""백준10039

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P-uZbG-7SJ9WRluT4a9nrNhdr48a4B_K
"""

# 평균 점수
sum = 0
for i in range(5):
    score = int(input())
    if score < 40:
        score = 40
    sum += score
print(int(sum/5))
