# -*- coding: utf-8 -*-
"""백준8958

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_waxrMGLFaUoZwVjdcx-cFDJH4uylBdQ
"""

# OX퀴즈
n = int(input())
for i in range(n):
    sum = 0
    score = 0
    s = input()
    for j in s:
        if j == 'O':
            score += 1
        else:
            score = 0
        sum += score
    print(sum)