# -*- coding: utf-8 -*-
"""백준15904

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVQxnF_4eopS1jMSLfl3j8LF3oewt9__
"""

# UCPC는 무엇의 약자일까?

s = input()
mylist = []
for i in s:
    if i == 'U':
        if len(mylist) == 0:
            mylist.append(i)
    if i == 'C':
        if len(mylist) == 1:
            mylist.append(i)
    if i == 'P':
        if len(mylist) == 2:
            mylist.append(i)
    if i == 'C':
        if len(mylist) == 3:
            mylist.append(i)

if mylist == ['U','C','P','C']:
    print('I love UCPC')
else:
    print('I hate UCPC')