# -*- coding: utf-8 -*-
"""백준13706

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1klXyEDJW5IuXOmHMcc0r8YLHNDNRWvXd
"""

# 제곱근
import sys

N = int(sys.stdin.readline())
left = 0
right = N
while 1:    # using Binary Search
    middle = (left + right) // 2
    if middle ** 2 == N:
        print(middle)
        break
    elif middle ** 2 > N:
        right = middle
    else:
        left = middle

