# -*- coding: utf-8 -*-
"""백준2525

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lg6m0W7RZfMjjkrY5dBejw4WeOW19nvz
"""

# 오븐 시계

A, B = map(int, input().split())
C = int(input())

cnt = 0
minute = B + (C % 60)
while minute >= 60:
    minute = minute % 60
    cnt += 1

hour = A + (C // 60)
hour += cnt
while hour >= 24:
    hour = hour % 24

print(hour, minute)