# -*- coding: utf-8 -*-
"""백준11659

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19IkcJ2AvzkkO4FOXBh9Ef_ZKawyACrIo
"""

# 구간 합 구하기 4

import sys
#input = sys.stdin.readline

N, M = map(int, input().split())
nums = list(map(int, input().split()))
dp = [0] * (N+1)
for i in range(1,N+1):
    dp[i] = dp[i-1] + nums[i-1]

for _ in range(M):
    i, j = map(int, input().split())
    print(dp[j]-dp[i-1])