# -*- coding: utf-8 -*-
"""백준7785

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Jkb-EIOSGSlXhMIhuL544TmAyvexdJp
"""

# 회사에 있는 사람
import sys
input = sys.stdin.readline
n = int(input())
in_out = {}
for _ in range(n):
    name, state = input().split()
    if state == 'enter':
        in_out[name] = 1
    else:
        in_out[name] = 0
for j in sorted((i for i,v in in_out.items() if v), reverse=True):
    print(j)