# -*- coding: utf-8 -*-
"""백준9613

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SOl_OjiuO0Kp2nZQ32korIXkgivpxd0N
"""

# GCD 합
'''
def get_gcd(n1, n2):
    gcd = 1
    for i in range(1, min(n1, n2)+1):
        if (n1 % i == 0) and (n2 % i == 0):
            gcd = i
    return gcd
'''
def get_gcd(n1, n2): # 유클리드 호제법
    while n2:
        n1, n2 = n2, n1 % n2
    return n1

T = int(input())
for i in range(T):
    N, *num_list = map(int, input().split())
    sum = 0
    for i in range(N-1):
        for j in range(1,N-i):
            sum += get_gcd(num_list[i], num_list[i+j])
    print(sum)