# -*- coding: utf-8 -*-
"""백준10809

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18zklZw9XzNuBjgc9akVVpqFznx1hZsDB
"""

# 알파벳 찾기

S = input()
a = ['a','b','c','d','e','f','g','h','i','j','k','l','m',
     'n','o','p','q','r','s','t','u','v','w','x','y','z']
check = [-1] * 26

for i in range(len(S)):
    if check[a.index(S[i])] == -1:
        check[a.index(S[i])] = i

for j in check:
    print(j, end=' ')