# -*- coding: utf-8 -*-
"""백준5430

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1icAFJSBFpyL5hlSWklbZjw-x9ZNgEa1m
"""

# AC
from sys import stdin

T = int(input())
for _ in range(T):
    p = stdin.readline().rstrip()
    n = int(stdin.readline())
    x = stdin.readline().rstrip()[1:-1].split(',')

    sum = 0
    pop_right = 0
    pop_left = 0
    for i in p:
        if i == 'R':
            sum += 1
        else:
            if sum % 2 == 0:
                pop_left += 1
            else:
                pop_right += 1
    if n >= pop_right + pop_left:
        x = x[pop_left:n-pop_right]
        if sum % 2 == 0:
            print('['+','.join(x)+']')
        else:
            print('['+','.join(x[::-1])+']')
    else:
        print('error')