# -*- coding: utf-8 -*-
"""백준11721

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HnQMGT84QkEMjzhqA2S6uW_ZbNnZ3RdT
"""

# 열 개씩 끊어 출력하기
s = input()
cnt = 0
for i in s:
    print(i, end='')
    cnt += 1
    if cnt % 10 == 0:
        print()