# -*- coding: utf-8 -*-
"""백준1002

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C18dRgxaRo_Nh8jgnibhL3lYE58-XHsQ
"""

# 터렛
T = int(input())
for i in range(T):
    x1, y1, r1, x2, y2, r2 = map(int, input().split())
    d = (((x1-x2)**2 + (y1-y2)**2)**(1/2))
    if x1 == x2 and y1 == y2 and r1 == r2:
        print(-1)
    elif d == r1 + r2 or d == abs(r1-r2):
        print(1)
    elif d > r1 + r2 or d < abs(r1-r2):
        print(0)
    else:
        print(2)