# -*- coding: utf-8 -*-
"""백준10826

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rm3Sk3kVLkuzbZjf5U7FtuIDofrS0Wjy
"""

# 피보나치 수 4
n = int(input())
fib = [0, 1]

for i in range(n):
    fib.append(fib[i]+fib[i+1])

print(fib[n])

def fibo(n):
    x, y = 0, 1
    for i in range(n):
        temp = x
        x = y
        y = temp + y
    return x

n = int(input())
print(fibo(n))