# -*- coding: utf-8 -*-
"""백준9012

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SIjqnorEI04G6gVKlCGObYxAiXzDTS3K
"""

# 괄호
T = int(input())
for i in range(T):
    result = 'YES'
    stack = []
    VPS = input()
    for i in VPS:
        if i == '(':
            stack.append(i)
        else:
            if not stack:
                result = 'NO'
                break
            else:
                if stack.pop() == ')':
                    result = 'NO'
                    break
    if stack:
        result = 'NO'
    print(result)