# -*- coding: utf-8 -*-
"""백준10250

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J8Cc2JZ3P1qUf3hkn4rGxHBw2Q1jsmMW
"""

# ACM 호텔
import sys

T = int(input())
for _ in range(T):
    H, W, N = map(int, input().split())
    cnt = 0
    for i in range(1, W+1):
        for j in range(1, H+1):
            cnt += 1
            if cnt == N:
                print(j*100 + i)
                break
        if cnt == N:
            break