# -*- coding: utf-8 -*-
"""백준1934

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/188HdcmwlCerbtNPQQ_IEqvlcONAaoYxR
"""

# 최소공배수

def gcd(a,b):      # 유클리드 호제법으로 최대공약수 구하는 메서드
    while b != 0:
        a, b = b, a % b
    return a

T = int(input())
for _ in range(T):
    A, B = map(int, input().split())
    print(gcd(A,B) * (A // gcd(A, B)) * (B // gcd(A, B)))