# -*- coding: utf-8 -*-
"""백준5543

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XEHweUPKN_IDxQHBhJ3U7E8fJlTMDLFm
"""

# 상근날드
sang = int(input())
jung = int(input())
ha = int(input())
coke = int(input())
saida = int(input())

print(min(sang, jung, ha) + min(coke, saida) - 50)