# -*- coding: utf-8 -*-
"""백준6603

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17WAH45BeSqkTxBaoVK7NzvHCPYab14gh
"""

# 로또
from itertools import combinations
import sys

while 1:
    k, *S = map(int, sys.stdin.readline().split())
    if k == 0:
        break
    for i in combinations(S,6):
        for j in i:
            print(j, end=' ')
        print()
    print()