# -*- coding: utf-8 -*-
"""백준18870

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19MFcFyMH3d-6QczYNFP1z9md6L8oM1Vz
"""

# 좌표 압축

N = int(input())
co = list(map(int, input().split()))
sorted_co = sorted(list(set(co)))
d = {sorted_co[i]: i for i in range(len(sorted_co))}
for i in co:
    print(d[i], end=' ')