# -*- coding: utf-8 -*-
"""백준10951

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mnJYIpoCzwDnqwBeyfC2wykhMH9ZHUoy
"""

# A + B -4
while (1):
    try:
        A, B = map(int, input().split())
        print(A+B)
    except:     # 실행안되면 중단
        break