# -*- coding: utf-8 -*-
"""백준20116

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aPXRYzAIcKo_VJetAho__4VyZIiGHv7o
"""

# 상자의 균형
n, L = map(int, input().split())
center = list(map(int, input().split()))

result = 'stable'
for j in range(len(center)-1):
    sum = 0
    for i in range(j+1, len(center)):
        sum += center[i]
    cen = sum / (len(center)-j-1)
    
    if (center[j] + L < cen) or (center[j] - L > cen):
        result = 'unstable'
        break
        
print(result)