# -*- coding: utf-8 -*-
"""백준20546

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeaZO1llr2kcF_1PZ-bJPHJtk1gB6yAb
"""

# 🐜 기적의 매매법 🐜
money = int(input())
hyeon_out = money
hyeon_in = 0
min_out = money
min_in = 0
chart = list(map(int, input().split()))

up_cnt = 0
down_cnt = 0
for i in range(len(chart)-1):
    if hyeon_out >= chart[i]:
        hyeon_in = chart[i]*(hyeon_out//chart[i])
        hyeon_out = hyeon_out - hyeon_in
    hyeon_in = (hyeon_in//chart[i]) * chart[i+1]  # 다음 날

for i in range(len(chart)-2):
    if chart[i] < chart[i+1]:
        up_cnt += 1
    else:
        up_cnt = 0
    if chart[i] > chart[i+1]:
        down_cnt += 1
    else:
        down_cnt = 0
    if up_cnt >= 3:     # 3일연속 상승
        min_out = min_out + min_in
        min_in = 0

    if down_cnt >= 3:   # 3일 연속 하락
        if min_out >= chart[i+1]:
            min_in = chart[i+1]*(min_out//chart[i+1])
            min_out = min_out - min_in
    min_in = (min_in//chart[i+1])*chart[i+2]   

if hyeon_in+hyeon_out > min_in+min_out:
    print('BNP')
elif hyeon_in+hyeon_out < min_in+min_out:
    print('TIMING')
else:
    print('SAMESAME')