# -*- coding: utf-8 -*-
"""백준1929

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MDPMZZK05AzUQ5VzkR7yA9M05TztiH2Q
"""

# 소수 구하기

def is_prime(n):
    if n == 1:
        return False
    if n == 2:
        return True
    for i in range(2,int(n**(1/2))+1):
        if n % i == 0:
            return False
    return True

M, N = map(int, input().split())
for i in range(M, N+1):
    if is_prime(i):
        print(i)