# -*- coding: utf-8 -*-
"""백준1978

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lRH8vWizGmI2tWjxpgHBTwfNA2AHJfVj
"""

# 소수 찾기
def is_prime(n):
    if n == 1:
        return False
    for i in range(2,int(n**(1/2))+1):
        if n % i == 0:
            return False
    return True

N = int(input())
num = list(map(int, input().split()))
count = 0
for i in num:
    if is_prime(i):
        count += 1
print(count)