# -*- coding: utf-8 -*-
"""백준4344

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RY7Upk1jUVq_t6IWCv2DgElKPrjL7C9_
"""

# 평균은 넘겠지
C = int(input())
for i in range(C):
    n, *s = map(int, input().split())
    sum = 0
    cnt = 0
    for j in range(n):
        sum += s[j]
    avg = sum / n    
    for k in range(n):
        if s[k] > avg:
            cnt += 1
    print("%.3f%%" %((cnt/n)*100))