# -*- coding: utf-8 -*-
"""백준21194

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pliFy2QjFA0Dqp8ECpftPrNk1HpdYTWP
"""

# Meditation
import sys
n, k = map(int, input().split())

num_list = []
for i in range(n):
    num = int(sys.stdin.readline())
    num_list.append(num)

sum = 0
num_list.sort(reverse=True)
for i in range(k):
    sum += num_list[i]

print(sum)