# -*- coding: utf-8 -*-
"""백준1225

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BV6BS9PP_P3fuaTd5-D7Clvu-VDU4QgX
"""

# 이상한 곱셈
A, B = input().split()
if len(A) < len(B):
    A , B = B, A

sum = 0
for i in A:
    sum += int(i)

total_sum = 0
for i in B:
    total_sum += int(i)*sum

print(total_sum)