# -*- coding: utf-8 -*-
"""백준9550

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16LnXWHWMRS58JB4gHhC9-RlFUyfNL9PQ
"""

# 아이들은 사탕을 좋아해

T = int(input())

for i in range(T):
    N, K = map(int, input().split())
    candy = list(map(int, input().split()))
    sum = 0
    for i in candy:
        sum += i // K
    print(sum)