# -*- coding: utf-8 -*-
"""백준4101

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MeM4pwRVDcGkZTmk4WSNu5sNgnqjJuev
"""

# 크냐?

a, b = map(int, input().split())
while (a != 0) or (b != 0):
    if a > b:
        print("Yes")
    else:
        print("No")
    a, b = map(int, input().split())