# -*- coding: utf-8 -*-
"""백준2417

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fL5QtOe_w3sQQPe43bHbpkbYvqc5swHa
"""

# 정수 제곱근

n = int(input())

if n**(1/2) % 1 == 0:
    print(int(n**(1/2)))
else:
    print(int(n**(1/2))+1)