# -*- coding: utf-8 -*-
"""백준1357

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15xpria2U_sVKWiY7vmH3jQGS-jVb6PjG
"""

# 뒤집힌 덧셈
def Rev(X):
    rev_X = X[::-1]
    return int(rev_X)

X, Y = input().split()
print(Rev(str(Rev(X)+Rev(Y))))