# -*- coding: utf-8 -*-
"""백준2309

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybRLcuw6-ZkkAuYAUqOAbtbutC2tBGbG
"""

# 일곱 난쟁이
import sys

small = []
for i in range(9):
    height = int(sys.stdin.readline())
    small.append(height)

sub = sum(small) - 100

for i in small:
    if (sub-i in small) and (i != sub-i):
        small.remove(i)
        small.remove(sub-i)
        break

for i in sorted(small):
    print(i)