# -*- coding: utf-8 -*-
"""백준15894

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NSdrR0UbR4_epoO6sQhFmOdZzCPBdXG1
"""

# 수학은 체육과목 입니다
n = int(input())
print(4*n)