# -*- coding: utf-8 -*-
"""백준1475

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-JM5Y6ulXuNXtMepkBnztBfy4GJb4Oa
"""

# 방 번호
number = {}
for i in range(10):
    number[str(i)] = 0
N = input()
for i in N:
    if i == '6' or i == '9':
        if number['6'] > number['9']:
            number['9'] += 1
        else:
            number['6'] += 1
    else:
        number[i] += 1
print(max(number.values()))