# -*- coding: utf-8 -*-
"""백준1024

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_akIrqGSuIJvWpWOsnL7JJJdWP70poOu
"""

# 수열의 합

N, L = map(int, input().split())
result = False
for i in range(L, 101):
    if i % 2 == 1:  # 홀수 길이일 때
        if N % i == 0:
            if N//i-(i//2) >= 0:
                result = True
                ans = range(N//i-(i//2), N//i+(i//2)+1)
                break
    else:           # 짝수 길이일 때
        if (N/i - 0.5) % 1 == 0:
            if N//i-i//2+1 >=0:
                result = True
                ans = range(N//i-i//2+1, N//i+i//2+1)
                break
if result:
    for i in ans:
        print(i, end=' ')
else:
    print(-1)