# -*- coding: utf-8 -*-
"""백준5532

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I6cx3KNYD3s73V9Qi0N_BFfe4kbqS7hM
"""

# 방학 숙제
L = int(input())
A = int(input())
B = int(input())
C = int(input())
D = int(input())
if (A/C) % 1 == 0:
    korean = A//C
else:
    korean = A//C+1
if (B/D) % 1 == 0:
    math = B//D
else:
    math = B//D+1    
result = L-max(korean, math)

if result < 0:
    print(0)
else:
    print(result)

10//3