# -*- coding: utf-8 -*-
"""백준2609

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N_DJHKJfcs-eZVKjYExjQXXFwLWBTVTM
"""

# 최대공약수와 최소공배수
def gcd(n1, n2):
    while n2 > 0:
        n1, n2 = n2, n1 % n2
    return n1
def lcm(n1, n2):
    g = gcd(n1, n2)
    return g * (n1//g) * (n2//g)

n1, n2 = map(int, input().split())

print(gcd(n1,n2))
print(lcm(n1,n2))

def gcd(n1, n2):
    while n2 > 0:
        n1, n2 = n2, n1 % n2
    return n1
def lcm(n1, n2):
    g = gcd(n1, n2)
    return g * (n1//g) * (n2//g)

lcm(18, 24)
        

# 15 12 == 60 // 20 30 60