# -*- coding: utf-8 -*-
"""백준2750

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bm6RMTkTM3D0GdBxDWX1iuL3adWaoVf-
"""

# 수 정렬하기

import sys

numbers = []
N = int(input())
for _ in range(N):
    numbers.append(int(sys.stdin.readline()))
for i in sorted(numbers):
    print(i)