# -*- coding: utf-8 -*-
"""백준18883

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IdmLbc06nBHNU2g9coDGuzJMXRekZIWV
"""

# N M 찍기

N, M = map(int, input().split())
for i in range(1, N*M+1):
    if i % M == 0:
        print(i, end='\n')
    else:
        print(i, end=' ')