# -*- coding: utf-8 -*-
"""백준1914

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WbnQrzpEybjxPTlDgM0htGqkq9p1LpbG
"""

# 하노이 탑
N = int(input())
def hanoi(n, f, t, temp):
    if n == 1:
        print(f, t)
        return
    hanoi(n-1, f, temp, t)
    print(f, t)
    hanoi(n-1, temp, t, f)

print(2**N-1)
if N <= 20:
    hanoi(N, 1, 3, 2)

1 << 4