# -*- coding: utf-8 -*-
"""백준2438

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLsf2_MpwyR-q1GhlGVf-YN5AZqJPoe1
"""

# 별 찍기 - 1
N = int(input())
for i in range(1,N+1):
    print('*'*i)