# -*- coding: utf-8 -*-
"""백준2748

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fciu56RIezrGaYBjjcEl7fRFePluptMF
"""

# 피보나치 수 2
fib = [0, 1]

n = int(input())
if n < 2 :
    print(fib[n])
else:
    for i in range(2, n+1):
        fib.append(fib[i-2]+fib[i-1])
    print(fib[i])