# -*- coding: utf-8 -*-
"""백준1764

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kktJCx9phbjKhZ8MrSyk_s76H-MVuCj2
"""

# 듣보잡
import sys
input = sys.stdin.readline
N, M = map(int, input().split())

listen = {}
both = []
for i in range(N):
    l = input().rstrip()
    listen[l] = 1

for i in range(M):
    try:
        watch = input().rstrip()
        listen[watch]
        both.append(watch)
    except:
        continue
print(len(both))
for i in sorted(both):
    print(i)