# -*- coding: utf-8 -*-
"""백준2751

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jqkTduvrTCehDEbRSks42EcrOGzkOQv
"""

# 수 정렬하기 2

import sys
input = sys.stdin.readline

N = int(input())
nums = []
for _ in range(N):
    num = int(input())
    nums.append(num)
for i in sorted(nums):
    print(i)