# -*- coding: utf-8 -*-
"""백준1011

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PN9tBaFZSXHVr1-H-Y8y5AKncySCrYz4
"""

# Fly me to the Alpha Centauri
import sys
import math

T = int(input())
for _ in range(T):
    x, y = map(int, sys.stdin.readline().split())
    distance = y - x
    std = math.sqrt(distance)
    if distance <= int(std)**2 + int(std) and std % 1 != 0:
        print(2*math.ceil(std)-2)
    else:
        print(2*math.ceil(std)-1)