# -*- coding: utf-8 -*-
"""백준1427

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RkkWrSnjj5-VvBtMeAcWYWSIfGdvkCUe
"""

# 소트인사이드
s = list(input())
a = []
for i in s:
    a.append(int(i))
a.sort(reverse=True)
for i in a:
    print(i, end='')