# -*- coding: utf-8 -*-
"""백준10867

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oJWYh7piaRmDC38LAp_vG7WjEpw6XNRd
"""

# 중복 빼고 정렬하기

N = int(input())
nums = set(map(int, input().split()))
for i in sorted(nums):
    print(i, end=' ')