# -*- coding: utf-8 -*-
"""백준1037

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S7592nJFzkj8m0zNB-g1_RgGO8LEwbCw
"""

# 약수
N = int(input())
divisor = list(map(int, input().split()))
if len(divisor) == 1:
    print(divisor[0]**2)
else:
    divisor.sort()
    print(divisor[0]*divisor[-1])