# -*- coding: utf-8 -*-
"""백준1652

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jDXS4G5QYRDBYiQ-Pf1P1hT4aPA4pBwF
"""

# 누울 자리를 찾아라

space = []

N = int(input())

for i in range(N):
    m = input()
    space.append(m)

point_x_cnt = 0
point_y_cnt = 0
x_cnt = 0
y_cnt = 0

for i in range(N): # 가로 count 세주는 명령
    for j in range(N):
        if space[i][j] == '.':
            point_x_cnt += 1
        else:
            if point_x_cnt >= 2:
                x_cnt += 1
            point_x_cnt = 0
    if point_x_cnt >= 2:
        x_cnt += 1
    point_x_cnt = 0

for i in range(N): # 세로 count 세주는 명령
    for j in range(N):
        if space[j][i] == '.':
            point_y_cnt += 1
        else:
            if point_y_cnt >= 2:
                y_cnt += 1
            point_y_cnt = 0
    if point_y_cnt >= 2:
        y_cnt += 1
    point_y_cnt = 0

print(x_cnt, y_cnt)