# -*- coding: utf-8 -*-
"""백준9086

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lYDPfN3fbWEsd9WLtBLY2A6CRUN22qU0
"""

# 문자열
n = int(input())

for i in range(n):
    s = input()
    print(s[0], s[-1], sep='')