# -*- coding: utf-8 -*-
"""백준2576

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/121ibfzRGr8UesC6Ol3J0zuaOA0jjnonH
"""

# 홀수

num_list = []
for i in range(7):
    num = int(input())
    if num % 2 == 1:
        num_list.append(num)

sum = 0
for i in num_list:
    sum += i

if len(num_list) == 0:
    print(-1)
else:
    print(sum)
    print(min(num_list))