# -*- coding: utf-8 -*-
"""백준10989

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HFA0GNEnZncUzr9ViISrI3JV8EKvIFWr
"""

# 수 정렬하기 3
import sys

N = int(input())
numbers = [0] * 10001
for _ in range(N):
    num = int(sys.stdin.readline())
    numbers[num] += 1

for i in range(len(numbers)):
    if numbers[i] != 0:
        for _ in range(numbers[i]):
            print(i)