# -*- coding: utf-8 -*-
"""백준1059

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cl8lT5mW7ublUpzAClPJ5Bshqa6M6OpM
"""

# 좋은 구간
L = int(input())
nums = list(map(int, input().split()))
n = int(input())
nums.sort()
if n in nums:
    print(0)
else:
    if len(nums) == 1:
        nums = [0,nums[0]]
    else:
        nums = [0] + nums
    for i in range(len(nums)):
        if n < nums[i]:
            if i == 0:
                idx = -1
                break
            idx = i-1
            break

    if nums[idx+1]-1 <= nums[idx]+1:
        print(0)
    else:
        sum = 0
        for i in range(nums[idx]+1, n+1):
            if i < n:
                sum += (nums[idx+1]-n)
            else:
                sum += (nums[idx+1]-n-1)
        print(sum)