# -*- coding: utf-8 -*-
"""백준2292

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168XmwzNCvDlB_Rk_wCW_XCISwq6dfCa3
"""

# 벌집
'''
 1 - 8 - 20 - 38 - 62 - 
   7   12   18   24  = 간격
 1 2 3   4    5    6 = 거리

'''
n = int(input())
i = 0
sum = 1
cnt = 0

while 1:
    if sum < n:
        sum += i
        i += 6
        cnt += 1
    else:
        break
if n == 1:
    cnt = 1

print(cnt)