# -*- coding: utf-8 -*-
"""백준1100

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MRIkOsp7JYCSs9zMWf_1s7w2trYr1Lik
"""

# 하얀 칸

cnt = 0
for i in range(8):
    chess = input()
    if i % 2 == 0:
        for j in range(8):
            if j % 2 == 0:
                if chess[j] == 'F':
                    cnt += 1
    else:
        for j in range(8):
            if j % 2 == 1:
                if chess[j] == 'F':
                    cnt += 1
print(cnt)