# -*- coding: utf-8 -*-
"""백준1541

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zoa7n_21yDBxEZwvxwvnqurEjxTCiJFy
"""

# 잃어버린 괄호
eq = input()
a = eq.split('-')
c = []
for i in a:
    b = i.split('+')
    sum = 0
    for j in b:
        sum += int(j)
    c.append(str(sum))

sum = int(c[0])
for i in range(1, len(c)):
    sum -= int(c[i])
print(sum)