# -*- coding: utf-8 -*-
"""백준10814

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RYFugWexGI4dqZ105LpKWVCaS5nu4XE8
"""

# 나이순 정렬
import sys
input = sys.stdin.readline

N = int(input())
people = []
for _ in range(N):
    age, name = input().split()
    age = int(age)
    people.append([age, name])

for i in sorted(people, key=lambda x:x[0]):
    print(i[0], i[1])