# -*- coding: utf-8 -*-
"""백준1904

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CWsx8lwEL1qQCILd9rXZr8d-_LokIg1L
"""

# 01타일
N = int(input())
a = 1
b = 1

for i in range(N-1):
    a, b = (a+b) % 15746, a % 15746
        
print(a)

# dp 리스트 사용
N = int(input())
dp = [1,2] + [0] * (N)

for i in range(N+1):
    if dp[i] == 0:
        dp[i] = (dp[i-1]+dp[i-2]) % 15746
        
print(dp[N-1])