# -*- coding: utf-8 -*-
"""백준20112

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f4rk04CPorWOWDpsLV_cTsjptxPe_-DE
"""

# 사토르 마방진

N = int(input())

result = True
word = []
for i in range(N):
    x = input()
    word.append(x)

for i in range(N):
    for j in range(N):
        if word[i][j] == word[j][i]:
            continue
        else:
            result = False

if result == True:
    print('YES')
else:
    print('NO')