# -*- coding: utf-8 -*-
"""백준11656

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6_6eByw0GR6fAZkXB82F4jdb6bsrGi3
"""

# 접미사 배열

S = input()
string_list = []
for i in range(len(S)):
    string_list.append(S[i:])
for i in sorted(string_list):
    print(i)