# -*- coding: utf-8 -*-
"""백준10870.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ri3ZuPfUkfx7EekT4jsPfbneZ2eC9YBN
"""

# 피보나치 수 5

n = int(input())
f = [0, 1]

for x in range(n):
    a = f[x] + f[x+1]
    f.append(a)

print(f[n])