# -*- coding: utf-8 -*-
"""백준1747

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LqXVHCW0sK6PZpXvH8pYT7ebriNtp9Ad
"""

# 소수 & 팰린드롬

def is_prime(n):
    if n == 1:
        return False
    for i in range(2,int(n**(1/2))+1):
        if n % i == 0:
            return False
    return True

def is_pal(s):
    if s == s[::-1]:
        return True
    else:
        return False

N = int(input())
n = N
while 1:
    if is_prime(n) and is_pal(str(n)):
        print(n)
        break
    else:
        n += 1