# -*- coding: utf-8 -*-
"""백준1546

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cBtYGRjlCPCCwfEYc_xnQa5YlS2yGX66
"""

# 평균
N = int(input())
score = list(map(int, input().split()))

sum = 0
for i in range(N):
    sum += score[i]/max(score)*100
print(sum/N)