# -*- coding: utf-8 -*-
"""백준2920

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wIuCoGOnTvof25p2Li-5YTKa42-7iVj2
"""

# 음계

k = list(map(int, input().split()))
if k == sorted(k):
    print('ascending')
elif k == sorted(k, reverse=True):
    print('descending')
else:
    print('mixed')