# -*- coding: utf-8 -*-
"""백준10845

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WruEkAxECfW-hCFcW714x7tGI9GndIrk
"""

# 큐
import sys
queue = []

N = int(input())
for i in range(N):
    s = sys.stdin.readline().split()    # sys.stdin.readline(): input()과 유사 (속도가 빠름)
    
    if s[0] == 'push':
        queue.append(int(s[1]))
    elif s[0] == 'front':
        if len(queue) == 0:
            print(-1)
        else:
            print(queue[0])
    elif s[0] == 'back':
        if len(queue) == 0:
            print(-1)
        else:
            print(queue[-1])
    elif s[0] == 'size':
        print(len(queue))
    elif s[0] == 'empty':
        if len(queue) == 0:
            print(1)
        else:
            print(0)
    elif s[0] == 'pop':
        if len(queue) == 0:
            print(-1)
        else:
            print(queue[0])
            queue.remove(queue[0])