# -*- coding: utf-8 -*-
"""백준11653

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MmIRVLkMBzQ0-EsUJbCy17imBuwImy7J
"""

# 소인수분해

N = int(input())
i = 2
while N > 1:
    if i > N**(1/2): # N의 제곱근만큼만 계산해주면 된다.
        print(N)
        break
    if N % i == 0:
        print(i)
        N = N // i
    else:
        i += 1