# -*- coding: utf-8 -*-
"""백준1297

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dnyk2vjzS2DpwYw69tmhodag0gmSESFk
"""

# TV 크기
diagonal, height_rate, width_rate = map(int, input().split())
# diagonal ** 2 = (height_rate ** 2 + width_rate ** 2) * a**2
x = diagonal ** 2 / (height_rate ** 2 + width_rate ** 2)
height = (x ** (1/2)) * height_rate
width = (x ** (1/2)) * width_rate
print(int(height), int(width))