# -*- coding: utf-8 -*-
"""백준2581

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GkGTL-f-Jk1KsIHbRfD3NHLITBqvQrrW
"""

# 소수

M = int(input())
N = int(input())

is_prime = [False, False, True] + [True] * (N-2)
for i in range(2, N//2+1):
    if is_prime[i]:
        for j in range(2*i, N+1, i):
            is_prime[j] = False
        
primes = []
for i in range(M, N+1):
    if is_prime[i]:
        primes.append(i)

if not primes:
    print(-1)
else:
    print(sum(primes))
    print(primes[0])