# -*- coding: utf-8 -*-
"""백준2495

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R2xrRkGetuAdTIGGhAupC5wUR7Ka-h28
"""

# 연속구간

for i in range(3):
    s = input()
    freq = []
    count = 1
    for i in range(len(s)-1):
        if s[i] == s[i+1]:
            count += 1
        else:
            freq.append(count)
            count = 1
    freq.append(count)
    print(max(freq))