# -*- coding: utf-8 -*-
"""백준10828

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_2J3b07zy2UY9dTlMZxsuRSPEuqnzAMj
"""

# 스택
import sys
stack = []
N = int(input())
for i in range(N):
    command = sys.stdin.readline().split()
    if command[0] == 'push':
        stack.append(int(command[1]))
    elif command[0] == 'top':
        if not stack:
            print(-1)
        else:
            print(stack[-1])
    elif command[0] == 'size':
        print(len(stack))
    elif command[0] == 'empty':
        if not stack:
            print(1)
        else:
            print(0)
    else:
        if not stack:
            print(-1)
        else:
            print(stack.pop())