# -*- coding: utf-8 -*-
"""백준1620

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_VdCeAbgAWd9oWfoukyZgfbPjwUqS-hJ
"""

# 나는야 포켓몬 마스터 이다솜
import sys
N, M = map(int, input().split())

pocket = {}

for i in range(1, N+1):
    n = sys.stdin.readline().strip()
    pocket[n] = i
rev = {v:k for k,v in pocket.items()}
for i in range(M):
    m = sys.stdin.readline().strip()
    if m in pocket: # 문자를 입력받을 때
        print(pocket[m])
    else:   # 숫자를 입력받을 때
        print(rev[int(m)])