# -*- coding: utf-8 -*-
"""백준20113

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1op7GbGuXLApHlkEpyul5JSCaCvr3IvX2
"""

# 긴급 회의
N = int(input())
vote_list = list(map(int, input().split()))
mylist = [0 for i in range(N)]

for i in vote_list:
    if i == 0:
        continue
    mylist[i-1] += 1

mylist_sorted = sorted(mylist, reverse = True)

if mylist_sorted[0] == mylist_sorted[1]:
    print('skipped')
else:
    print(mylist.index(max(mylist))+1)