# -*- coding: utf-8 -*-
"""백준10610

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QHbYQgAGOIwTW0TUjhnQSPKfFm7x32ra
"""

# 30

N = str(input())
if '0' not in N:
    print(-1)
else:
    sum = 0
    for i in N:
        sum += int(i)
    if sum % 3 == 0:
        for i in sorted(N, reverse=True):
            print(i, end='')
    else:
        print(-1)