# -*- coding: utf-8 -*-
"""백준2747

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12jS9wLnX2f_T0u4nNEpYWvTjwepa1xQo
"""

# 피보나치 수
d = [0] * 46
def dp(N):
    if N == 0:
        return 0
    if N == 1:
        return 1
    if d[N] != 0:
        return d[N]
    d[N] = dp(N-1) + dp(N-2)
    return dp(N-1) + dp(N-2)

n = int(input())
print(dp(n))