# -*- coding: utf-8 -*-
"""백준1644

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MglG5NC886Tu3us0zu8yDzhfmE5iNe4G
"""

# 소수의 연속합

N = int(input())

is_prime = [False, False, True] + [True] * (N-2)
for i in range(2, int(N**0.5)+1):
    if is_prime[i]:
        for j in range(2*i, N+1, i):
            is_prime[j] = False
primes = [i for i in range(2, N+1) if is_prime[i]]
primes.reverse()

cnt = 0
for i in range(len(primes)):
    sum = 0
    for j in range(i, len(primes)):
        sum += primes[j]
        if sum == N:
            cnt += 1
            break
        elif sum > N:
            break

print(cnt)