# -*- coding: utf-8 -*-
"""백준10825

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gqqJz47pr78JHNNrOBM2TFZmSRaAVL2R
"""

# 국영수
import sys

scores = []
N = int(input())
for _ in range(N):
    name, kor, eng, math = sys.stdin.readline().split()
    scores.append([name, int(kor), int(eng), int(math)])

for i in sorted(scores, key=lambda x: (-x[1], x[2], -x[3], x[0])):
    print(i[0])