# -*- coding: utf-8 -*-
"""백준10869

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QF3Cranf_niV9U8tCZJ-Ilgxm8zBHLAj
"""

# 사칙연산
A, B = map(int, input().split())
print(A+B)
print(A-B)
print(A*B)
print(int(A/B))
print(A%B)