# -*- coding: utf-8 -*-
"""백준13116

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GX07dn9kqemDu0qS9LFgmERnC0PQEi8u
"""

# 30번
import sys

def solve(T):
    A, B = map(int, sys.stdin.readline().split())
    A = min(A,B)
    while A > 0:
        B = max(A,B)
        while B >= A:
            if B == A:
                print(10*B)
                return
            B = B//2
        A = A//2

T = int(input())
for _ in range(T):
    solve(T)

