# -*- coding: utf-8 -*-
"""백준1356

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ks1mdyDsH2Qj4rDuoauJJt-uMNCMIlO3
"""

# 유진수
A = 'NO'
N = input()

for i in range(1, len(N)):
    mult1 = 1
    mult2 = 1
    for j in N[i:]:
        mult1 *= int(j)
    for k in N[:i]:
        mult2 *= int(k)
    if mult1 == mult2:
        A = 'YES'

print(A)