# -*- coding: utf-8 -*-
"""백준2355

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14J_60zh8qqtaDmYqczwLqMiUXoNV5lAN
"""

# 시그마

a, b = map(int, input().split())
m = max(a,b)
n = min(a,b)
if n >= 0 and m >= 0:
    sum = (m*(m+1))//2 - (n*(n+1))//2 + n
elif n < 0 and m >= 0:
    n = abs(n)
    sum = -((n*(n+1))//2) + (m*(m+1))//2
elif n < 0 and m < 0:
    n = abs(n)
    m = abs(m)
    sum = -((n*(n+1))//2 -(m*(m+1))//2 + m)

print(sum)