# -*- coding: utf-8 -*-
"""백준2562

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpgdOpSEJNfDjrZCvmNIWQ6BqqHFC5yP
"""

# 최댓값
num = int(input())
max = num
max_index = 1
for i in range(2,10):
    num = int(input())
    if max < num:
        max = num
        max_index = i
print(max)
print(max_index)