# -*- coding: utf-8 -*-
"""백준10998

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqp6fP4GxxbDwyxS6j2pRreCMNIbmNHJ
"""

# A x B
A, B = map(int, input().split())
print(A*B)