# -*- coding: utf-8 -*-
"""백준7770

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ePqtk_3GQ-_omc7r2Zi9IPrTqY3lpBZI
"""

# 아즈텍 피라미드
'''  1+3+5+7+9+11+9+7+5+3+1 = 61 -> 바닥 -20
    +1+3+5+7+9+7+5+3+1 =     41 2층 -16
    +1+3+5+7+5+3+1 =        25 3층 -12
    +1+3+5+3+1 =          13 4층  -8 
    +1+3+1 =             5 5층 --4
    +1 =                1''' # 꼭대기
n = int(input()) 
cnt = 0 #층 수
sum = 1
sum_0 = sum
for i in range(4, 100000000, 4):
    if sum_0 > n:
        break
    sum += i
    sum_0 += sum
    cnt += 1
print(cnt)