# -*- coding: utf-8 -*-
"""백준1920

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n3WCd1sPJc9zNcEiM-Dn99d1uHMuIVxh
"""

# 수 찾기
from collections import defaultdict

N = int(input())
A = defaultdict(int)
for i in map(int, input().split()):
    A[i] = 1
M = int(input())
for i in map(int, input().split()):
    if A[i] == 1:
        print(1)
    else:
        print(0)