# -*- coding: utf-8 -*-
"""백준10773

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y1lQiVi-p5bwepUVRHtMKPqAv1Mamuzp
"""

# 제로
import sys

K = int(input())
stack = []
for i in range(K):
    num = int(sys.stdin.readline())
    if num == 0:
        if len(stack) != 0:
            stack.pop()
    else:
        stack.append(num)
print(sum(stack))