# -*- coding: utf-8 -*-
"""백준11650

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tc5Q49Qy6u5HTrvCZT4vuIgHskM5JMHy
"""

# 좌표 정렬하기

import sys
input = sys.stdin.readline

N = int(input())
arrs = []
for _ in range(N):
    arr = list(map(int, input().split()))
    arrs.append(arr)

for i in sorted(arrs, key=lambda x: (x[0], x[1])):
    print(i[0], i[1])